'use client';
import React,{useEffect,useState} from 'react';
import {dataService} from '@/lib/data-service';
import {LogisticsRequest} from '@/types';
import {ArrowLeft,QrCode,Truck,MapPin,ShieldCheck} from 'lucide-react';
import Link from 'next/link';
export default function GatePassPage({params}:{params:{orderId:string}}){
 const [job,setJob]=useState<LogisticsRequest|null>(null);
 useEffect(()=>{void (async()=>{const rows=await dataService.getLogisticsRequests();setJob(rows.find(r=>r.order_id===params.orderId)||null);})();},[params.orderId]);
 return <div className="mx-auto max-w-2xl space-y-5"><Link href="/logistics/deliveries" className="inline-flex items-center gap-2 text-xs text-gray-400 hover:text-white"><ArrowLeft className="h-4 w-4"/> Delivery Board</Link><section className="rounded-3xl border border-[#294238] bg-[#121a16] p-6 text-center shadow-xl"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-950 text-emerald-400"><QrCode className="h-8 w-8"/></div><p className="mt-4 text-[10px] font-bold uppercase tracking-[.2em] text-emerald-400">AgriMark Dock Gate Pass</p>{job?<><h1 className="mt-2 text-2xl font-bold text-white">{job.crop_name}</h1><p className="mt-1 text-xs text-gray-500">{Number(job.weight_kg||0).toLocaleString('en-IN')} kg · {job.tracking_code}</p><div className="mx-auto my-6 flex h-44 w-44 items-center justify-center rounded-2xl border-2 border-dashed border-emerald-700 bg-[#0a0f0d]"><div className="text-center"><QrCode className="mx-auto h-24 w-24 text-emerald-400"/><p className="mt-2 font-mono text-[9px] text-gray-500">SCAN AT DOCK</p></div></div><div className="grid gap-2 text-left md:grid-cols-2"><div className="rounded-xl bg-[#0a0f0d] p-3"><p className="text-[9px] uppercase text-gray-500">Pickup</p><p className="mt-1 text-xs font-semibold text-white">{job.pickup_location}</p></div><div className="rounded-xl bg-[#0a0f0d] p-3"><p className="text-[9px] uppercase text-gray-500">Destination</p><p className="mt-1 text-xs font-semibold text-white">{job.delivery_location}</p></div></div><div className="mt-4 flex items-center justify-center gap-2 text-[10px] text-gray-500"><Truck className="h-3.5 w-3.5"/> {job.vehicle_type}{job.driver_name?' · '+job.driver_name:''}</div></>:<div className="py-12 text-sm text-gray-500">No shipment is linked to this order.</div>}<div className="mt-5 flex items-center justify-center gap-2 text-[10px] text-emerald-400"><ShieldCheck className="h-3.5 w-3.5"/> Gate pass is derived from the shipment record</div></section></div>;
}