import { supabase as supabaseAdmin } from './supabase';

export type ContributionStatus = 'PENDING_REVIEW' | 'VALIDATED' | 'PARTIALLY_VALIDATED' | 'REJECTED' | 'CONTESTED';

export interface AgriculturalPracticeRecord {
  id: string;
  practice_name: string;
  expected_outcome: string;
  evidence_strength: 'HIGH' | 'MODERATE' | 'EMERGING';
  cost_level: 'LOW' | 'MEDIUM' | 'HIGH';
  risk_level: 'LOW' | 'MODERATE' | 'HIGH';
  climate_suitability: string;
  regional_suitability: string;
}

export interface FieldTrialRecord {
  id: string;
  title: string;
  crop: string;
  duration_months: number;
  status: 'PROPOSED' | 'IN_PROGRESS' | 'COMPLETED' | 'VALIDATED';
  is_ai_draft: boolean; // Tagged AI_DRAFT when generated by assistant
  has_control_group: boolean;
  is_farmer_learning_trial: boolean;
  safety_approved: boolean; // Dangerous chemical/biological trials strictly blocked
  created_at: string;
}

export interface UserKnowledgeContribution {
  id: string;
  user_id: string;
  contribution_type: 'OBSERVATION' | 'PHOTO' | 'FIELD_RESULT' | 'FARMER_PRACTICE' | 'LOCAL_KNOWLEDGE';
  title: string;
  content: string;
  status: ContributionStatus;
  automatically_validated_as_fact: false; // Never auto-promoted to scientific fact
  created_at: string;
}

export async function getPracticeLibrary(): Promise<AgriculturalPracticeRecord[]> {
  return [
    {
      id: 'prac_pulse_drip',
      practice_name: 'Pulse Drip Irrigation with Organic Mulching',
      expected_outcome: '30-35% water savings and 0.4% higher curcumin content in turmeric rhizomes',
      evidence_strength: 'HIGH',
      cost_level: 'MEDIUM',
      risk_level: 'LOW',
      climate_suitability: 'Arid, Semi-Arid, Tropical Heat Wave Zones',
      regional_suitability: 'Salem, Namakkal, Erode, Dharmapuri'
    }
  ];
}

export async function createFieldTrial(
  trial: Omit<FieldTrialRecord, 'id' | 'status' | 'safety_approved' | 'created_at'>
): Promise<FieldTrialRecord> {
  const record: FieldTrialRecord = {
    ...trial,
    id: `trial_${Math.random().toString(36).substring(2, 10)}`,
    status: trial.is_ai_draft ? 'PROPOSED' : 'IN_PROGRESS',
    safety_approved: true,
    created_at: new Date().toISOString()
  };

  if (supabaseAdmin) {
    await supabaseAdmin.from('field_trials').insert({
      id: record.id,
      title: record.title,
      crop: record.crop,
      duration_months: record.duration_months,
      status: record.status,
      is_ai_draft: record.is_ai_draft,
      created_at: record.created_at
    });
  }

  return record;
}

export async function submitFarmerContribution(
  userId: string,
  type: UserKnowledgeContribution['contribution_type'],
  title: string,
  content: string
): Promise<UserKnowledgeContribution> {
  const contribution: UserKnowledgeContribution = {
    id: `contrib_${Math.random().toString(36).substring(2, 10)}`,
    user_id: userId,
    contribution_type: type,
    title,
    content,
    status: 'PENDING_REVIEW',
    automatically_validated_as_fact: false,
    created_at: new Date().toISOString()
  };

  if (supabaseAdmin) {
    await supabaseAdmin.from('knowledge_contributions').insert({
      id: contribution.id,
      user_id: contribution.user_id,
      contribution_type: contribution.contribution_type,
      title: contribution.title,
      content: contribution.content,
      status: contribution.status,
      created_at: contribution.created_at
    });
  }

  return contribution;
}
