import {
  UserProfile,
  Farm,
  CropCatalogItem,
  Cultivation,
  FieldObservation,
  HarvestBatch,
  ProduceLot,
  Listing,
  MarketplaceOrder,
  RFQ,
  Offer,
  MarketPriceObservation,
  WeatherForecast,
  FinanceRecord,
  FarmTask,
  FarmerDocument,
  ColdStorage,
  LogisticsRequest,
} from '@/types';

export const SEED_PROFILES: UserProfile[] = [
  {
    id: 'user-farmer-01',
    email: 'farmer.raman@agrimark.in',
    full_name: 'Ramanathan K.',
    phone: '+91 98765 43210',
    role: 'farmer',
    village: 'Vadapalani',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    location: 'Thanjavur, Tamil Nadu',
    kyc_status: 'verified',
    avatar_url: 'https://images.unsplash.com/photo-1595273670150-bd0c3c392e46?w=150',
    created_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-buyer-01',
    email: 'procurement@freshgro.com',
    full_name: 'Anand Sharma (FreshGro Retail)',
    phone: '+91 98123 45678',
    role: 'buyer',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    location: 'Bengaluru, Karnataka',
    kyc_status: 'verified',
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'user-fpo-01',
    email: 'secretary@kaveri-fpo.org',
    full_name: 'Kaveri Delta Farmers Producer Co.',
    phone: '+91 94440 11223',
    role: 'fpo',
    district: 'Nagapattinam',
    state: 'Tamil Nadu',
    location: 'Nagapattinam, Tamil Nadu',
    kyc_status: 'verified',
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'user-logistics-01',
    email: 'dispatch@greenline-logistics.in',
    full_name: 'GreenLine Agri Transport',
    phone: '+91 97890 55443',
    role: 'logistics',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    location: 'Coimbatore, Tamil Nadu',
    kyc_status: 'verified',
    created_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 'user-admin-01',
    email: 'admin@agrimark.in',
    full_name: 'AgriMark Systems Admin',
    phone: '+91 90000 00000',
    role: 'admin',
    location: 'National Operations Center',
    kyc_status: 'verified',
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const SEED_FARMS: Farm[] = [
  {
    id: 'farm-01',
    owner_id: 'user-farmer-01',
    name: 'Kaveri Green Paddy Fields',
    village: 'Papanasam',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    latitude: 10.9254,
    longitude: 79.2731,
    location: 'Papanasam, Thanjavur, Tamil Nadu',
    area_acres: 6.5,
    soil_type: 'Alluvial Clay Loam',
    irrigation_source: 'Canal & Borewell',
    water_source: 'Grand Anicut Canal',
    electricity_available: true,
    tenancy_type: 'owned',
    infrastructure: ['Borewell Pump', 'Drip Lines', 'Storage Shed', 'Solar Fencing'],
    created_at: '2026-01-15T09:00:00Z',
  },
  {
    id: 'farm-02',
    owner_id: 'user-farmer-01',
    name: 'Sundaram Organic Orchard',
    village: 'Orathanadu',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    latitude: 10.6271,
    longitude: 79.2458,
    location: 'Orathanadu, Thanjavur, Tamil Nadu',
    area_acres: 4.0,
    soil_type: 'Red Sandy Loam',
    irrigation_source: 'Drip Irrigation',
    water_source: 'Deep Submersible Well',
    electricity_available: true,
    tenancy_type: 'owned',
    infrastructure: ['Drip Irrigation Unit', 'Compost Pit', 'Solar Pump'],
    created_at: '2026-02-01T09:00:00Z',
  },
];

export const SEED_CROP_CATALOG: CropCatalogItem[] = [
  { id: 'crop-paddy', name: 'Paddy (Rice)', hindi_name: 'धान', tamil_name: 'நெல்', category: 'Cereals', typical_duration_days: 120, season: 'Kharif', agronomy_tips: 'Maintain 5cm standing water during tillering stage.' },
  { id: 'crop-cotton', name: 'Cotton', hindi_name: 'कपास', tamil_name: 'பருத்தி', category: 'Cash Crops', typical_duration_days: 160, season: 'Kharif', agronomy_tips: 'Monitor regularly for pink bollworm pest attack.' },
  { id: 'crop-turmeric', name: 'Turmeric', hindi_name: 'हल्दी', tamil_name: 'மஞ்சள்', category: 'Spices', typical_duration_days: 240, season: 'Perennial', agronomy_tips: 'High organic mulch application boosts curcumin content.' },
  { id: 'crop-tomato', name: 'Tomato', hindi_name: 'टमाटर', tamil_name: 'தக்காளி', category: 'Vegetables', typical_duration_days: 90, season: 'Rabi', agronomy_tips: 'Staking plants prevents soil-borne fungal infections.' },
  { id: 'crop-banana', name: 'Banana (Grand Naine)', hindi_name: 'केला', tamil_name: 'வாழை', category: 'Fruits', typical_duration_days: 330, season: 'Perennial', agronomy_tips: 'Apply potassium sulphate during bunch development.' },
];

export const SEED_CULTIVATIONS: Cultivation[] = [
  {
    id: 'cultivation-01',
    farm_id: 'farm-01',
    crop_id: 'crop-paddy',
    crop_name: 'Paddy (CR-1009 Sub1)',
    variety: 'CR-1009 Submariner',
    season: 'Samba / Thaladi',
    sowing_date: '2025-10-15',
    expected_harvest_date: '2026-02-20',
    area_acres: 5.0,
    expected_yield_kg: 12500,
    status: 'active',
    organic_practice: false,
    seed_variety: 'Certified TNAU Seed',
    agronomy_notes: 'Applied neem-coated urea on day 45. Excellent crop stand.',
    budget_inr: 85000,
    created_at: '2025-10-15T00:00:00Z',
  },
  {
    id: 'cultivation-02',
    farm_id: 'farm-02',
    crop_id: 'crop-turmeric',
    crop_name: 'Erode Local Turmeric',
    variety: 'Erode Finger Turmeric',
    season: 'Annual',
    sowing_date: '2025-06-01',
    expected_harvest_date: '2026-02-10',
    area_acres: 3.5,
    expected_yield_kg: 8750,
    status: 'harvested',
    organic_practice: true,
    seed_variety: 'Organic Rhizome Mother Seed',
    agronomy_notes: '100% Panchagavya and Vermicompost applied.',
    budget_inr: 120000,
    created_at: '2025-06-01T00:00:00Z',
  },
];

export const SEED_OBSERVATIONS: FieldObservation[] = [
  {
    id: 'obs-01',
    cultivation_id: 'cultivation-01',
    farm_id: 'farm-01',
    crop_stage: 'Grain Filling Stage',
    plant_health_score: 9,
    pest_pressure: 'low',
    disease_pressure: 'none',
    weed_pressure: 'low',
    soil_moisture_pct: 78,
    rainfall_mm: 12.5,
    temp_c: 29.5,
    notes: 'Grain formation uniform across all 5 acres. No sign of stem borer.',
    observed_at: '2026-02-05T10:30:00Z',
  },
];

export const SEED_HARVEST_BATCHES: HarvestBatch[] = [
  {
    id: 'harvest-01',
    cultivation_id: 'cultivation-02',
    harvest_date: '2026-02-12',
    total_quantity_kg: 8500,
    quality_grade: 'Grade A',
    moisture_pct: 11.2,
    rejection_pct: 1.5,
    packaging_type: '50kg Jute Gunny Bags',
    storage_requirement: 'Dry ventilated shed, below 12% moisture',
    trace_code: 'PASSPORT-TAMIL-TURMERIC-2026-001',
    created_at: '2026-02-12T14:00:00Z',
  },
];

export const SEED_PRODUCE_LOTS: ProduceLot[] = [
  {
    id: 'lot-01',
    owner_id: 'user-farmer-01',
    harvest_batch_id: 'harvest-01',
    cultivation_id: 'cultivation-02',
    crop_id: 'crop-turmeric',
    crop_name: 'Organic Finger Turmeric',
    quantity: 8500,
    quantity_kg: 8500,
    unit: 'kg',
    quality_grade: 'Grade A (Curcumin 4.8%)',
    available_quantity: 6000,
    harvest_date: '2026-02-12',
    storage_location: 'Central Cold Storage, Thanjavur',
    trace_code: 'PASSPORT-TAMIL-TURMERIC-2026-001',
    is_listed: true,
    status: 'available',
    created_at: '2026-02-12T15:00:00Z',
  },
  {
    id: 'lot-02',
    owner_id: 'user-farmer-01',
    crop_id: 'crop-paddy',
    crop_name: 'CR-1009 Sub1 Paddy',
    quantity: 12000,
    quantity_kg: 12000,
    unit: 'kg',
    quality_grade: 'Export Grade A',
    available_quantity: 12000,
    harvest_date: '2026-02-20',
    storage_location: 'Farm Granary, Papanasam',
    trace_code: 'PASSPORT-TAMIL-PADDY-2026-002',
    is_listed: true,
    status: 'available',
    created_at: '2026-02-20T11:00:00Z',
  },
];

export const SEED_LISTINGS: Listing[] = [
  {
    id: 'list-01',
    seller_id: 'user-farmer-01',
    lot_id: 'lot-01',
    produce_lot_id: 'lot-01',
    title: 'Premium Organic Finger Turmeric (Curcumin > 4.5%)',
    price_per_unit: 145,
    price_per_kg: 145,
    currency: 'INR',
    min_order_quantity: 500,
    min_order_quantity_kg: 500,
    crop_name: 'Turmeric',
    crop_category: 'Spices',
    quantity_available_kg: 6000,
    quality_grade: 'Grade A Organic',
    location: 'Thanjavur, Tamil Nadu',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    seller_name: 'Ramanathan K.',
    seller_rating: 4.9,
    images: [
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600',
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600',
    ],
    description: 'Directly harvested from certified organic farms in Thanjavur. High curcumin content, steam cleaned, stored under temperature control.',
    status: 'active',
    created_at: '2026-02-14T10:00:00Z',
  },
  {
    id: 'list-02',
    seller_id: 'user-farmer-01',
    lot_id: 'lot-02',
    produce_lot_id: 'lot-02',
    title: 'Samba CR-1009 Sub1 Paddy (Clean Dry Grain)',
    price_per_unit: 26.5,
    price_per_kg: 26.5,
    currency: 'INR',
    min_order_quantity: 1000,
    min_order_quantity_kg: 1000,
    crop_name: 'Paddy (Rice)',
    crop_category: 'Cereals',
    quantity_available_kg: 12000,
    quality_grade: 'Grade A',
    location: 'Papanasam, Thanjavur',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    seller_name: 'Ramanathan K.',
    seller_rating: 4.9,
    images: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600',
    ],
    description: 'Freshly harvested Samba paddy. Moisture level strictly below 13.5%. Cleaned and ready for rice millers or bulk grain buyers.',
    status: 'active',
    created_at: '2026-02-21T09:00:00Z',
  },
];

export const SEED_ORDERS: MarketplaceOrder[] = [
  {
    id: 'ord-1001',
    listing_id: 'list-01',
    listing_title: 'Premium Organic Finger Turmeric',
    buyer_id: 'user-buyer-01',
    buyer_name: 'Anand Sharma (FreshGro Retail)',
    seller_id: 'user-farmer-01',
    seller_name: 'Ramanathan K.',
    quantity: 2500,
    quantity_kg: 2500,
    unit: 'kg',
    unit_price: 145,
    total_amount: 362500,
    total_price: 362500,
    status: 'in_transit',
    payment_status: 'escrowed',
    delivery_address: 'FreshGro Regional Warehouse, Electronic City, Bengaluru',
    created_at: '2026-02-25T14:30:00Z',
  },
];

export const SEED_RFQS: RFQ[] = [
  {
    id: 'rfq-01',
    buyer_id: 'user-buyer-01',
    buyer_name: 'FreshGro Procurement Division',
    crop_name: 'Red Chilli (Sanam / Byadgi)',
    required_quantity_kg: 5000,
    target_price_per_kg: 180,
    quality_grade: 'Stemless Grade A',
    location: 'Bengaluru Delivery Hub',
    needed_by_date: '2026-03-25',
    status: 'open',
    created_at: '2026-03-01T09:00:00Z',
  },
];

export const SEED_OFFERS: Offer[] = [
  {
    id: 'off-01',
    rfq_id: 'rfq-01',
    seller_id: 'user-fpo-01',
    seller_name: 'Kaveri Delta FPO',
    offered_price_per_kg: 182,
    quantity_offered_kg: 5000,
    terms: 'Includes moisture test report & transport to Bengaluru warehouse',
    status: 'pending',
    created_at: '2026-03-02T11:00:00Z',
  },
];

export const SEED_MARKET_PRICES: MarketPriceObservation[] = [
  {
    id: 'price-01',
    crop_id: 'crop-paddy',
    commodity: 'Paddy (Common)',
    mandi_name: 'Thanjavur Main Regulated Mandi',
    market_name: 'Thanjavur Mandi',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    observation_date: '2026-03-14',
    observed_at: '2026-03-14T06:00:00Z',
    min_price: 2350,
    modal_price: 2480,
    max_price: 2600,
    unit: 'Quintal (100kg)',
    source: 'AGMARKNET Official Feed',
    source_name: 'AGMARKNET / Govt of India',
  },
  {
    id: 'price-02',
    crop_id: 'crop-turmeric',
    commodity: 'Turmeric (Finger)',
    mandi_name: 'Erode Regulated Market Complex',
    market_name: 'Erode Mandi',
    district: 'Erode',
    state: 'Tamil Nadu',
    observation_date: '2026-03-14',
    observed_at: '2026-03-14T06:30:00Z',
    min_price: 13200,
    modal_price: 14500,
    max_price: 15800,
    unit: 'Quintal (100kg)',
    source: 'Erode Spices Board Reference',
    source_name: 'Spices Board India',
  },
  {
    id: 'price-03',
    crop_id: 'crop-cotton',
    commodity: 'Cotton (Long Staple)',
    mandi_name: 'Guntur APMC Market',
    market_name: 'Guntur APMC',
    district: 'Guntur',
    state: 'Andhra Pradesh',
    observation_date: '2026-03-14',
    observed_at: '2026-03-14T07:00:00Z',
    min_price: 7200,
    modal_price: 7650,
    max_price: 8100,
    unit: 'Quintal (100kg)',
    source: 'AGMARKNET / AP Cotton Board',
    source_name: 'AGMARKNET',
  },
];

export const SEED_WEATHER: WeatherForecast[] = [
  {
    location: 'Thanjavur Delta Region',
    district: 'Thanjavur',
    date: '2026-03-15',
    temp_c: 32,
    temp_min_c: 24,
    temp_max_c: 34,
    condition: 'Partly Cloudy',
    humidity_pct: 68,
    rainfall_mm: 2.0,
    wind_speed_kmh: 14,
    crop_warning: 'Moderate humidity. Monitor paddy crops for early sheath blight.',
    alert_level: 'advisory',
  },
  {
    location: 'Thanjavur Delta Region',
    district: 'Thanjavur',
    date: '2026-03-16',
    temp_c: 33,
    temp_min_c: 25,
    temp_max_c: 35,
    condition: 'Sunny',
    humidity_pct: 62,
    rainfall_mm: 0,
    wind_speed_kmh: 12,
    crop_warning: 'Favorable condition for harvesting finger turmeric.',
    alert_level: 'normal',
  },
];

export const SEED_FINANCE: FinanceRecord[] = [
  {
    id: 'fin-01',
    user_id: 'user-farmer-01',
    farm_id: 'farm-01',
    type: 'expense',
    category: 'Seeds',
    amount: 14500,
    transaction_date: '2025-10-14',
    payment_status: 'paid',
    description: 'Certified CR-1009 Sub1 Paddy Seed from TNAU extension center',
    reference_no: 'INV-TNAU-8892',
  },
  {
    id: 'fin-02',
    user_id: 'user-farmer-01',
    farm_id: 'farm-02',
    type: 'income',
    category: 'Crop Sales',
    amount: 362500,
    transaction_date: '2026-02-25',
    payment_status: 'pending',
    description: 'Sale of 2.5 Tons Organic Turmeric to FreshGro (Escrowed)',
    reference_no: 'ORD-1001-ESCROW',
  },
];

export const SEED_TASKS: FarmTask[] = [
  {
    id: 'task-01',
    user_id: 'user-farmer-01',
    farm_id: 'farm-01',
    title: 'Borewell pump inspection & solar inverter check',
    description: 'Clean solar panels and check motor oil levels before irrigation shift.',
    due_date: '2026-03-16',
    priority: 'high',
    status: 'pending',
    category: 'Irrigation',
  },
  {
    id: 'task-02',
    user_id: 'user-farmer-01',
    farm_id: 'farm-02',
    title: 'Bagging & moisture check for harvested turmeric lot',
    description: 'Ensure moisture level is checked with digital meter before transport.',
    due_date: '2026-03-17',
    priority: 'urgent',
    status: 'in_progress',
    category: 'Harvesting',
  },
];

export const SEED_DOCUMENTS: FarmerDocument[] = [
  {
    id: 'doc-01',
    user_id: 'user-farmer-01',
    doc_type: 'Land Record (Patta/Chitta)',
    doc_number: 'PATTA-TN-THJ-2024-889',
    issuing_authority: 'Revenue Department, Govt of Tamil Nadu',
    issue_date: '2024-05-10',
    verification_status: 'verified',
    file_url: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=600',
    extracted_info: 'Land Area: 6.5 Acres in Papanasam Taluk. Registered Owner: Ramanathan K.',
    is_private: true,
  },
  {
    id: 'doc-02',
    user_id: 'user-farmer-01',
    doc_type: 'Organic Certification',
    doc_number: 'NPOP/NAB/0012/2025',
    issuing_authority: 'APEDA Approved Certification Body',
    issue_date: '2025-01-15',
    expiry_date: '2027-01-14',
    verification_status: 'verified',
    file_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
    extracted_info: 'Certified NPOP Organic Farm for Turmeric & Pulses.',
    is_private: false,
  },
];

export const SEED_COLD_STORAGE: ColdStorage[] = [
  {
    id: 'cs-01',
    name: 'Kaveri Delta Agro Cold Logistics Park',
    district: 'Thanjavur',
    state: 'Tamil Nadu',
    total_capacity_tons: 1500,
    available_capacity_tons: 420,
    temp_range_c: '4°C to 12°C',
    humidity_range_pct: '55% to 70%',
    price_per_ton_day: 45,
    contact_phone: '+91 94433 88776',
  },
  {
    id: 'cs-02',
    name: 'Coimbatore Spices & Produce Storage Ltd.',
    district: 'Coimbatore',
    state: 'Tamil Nadu',
    total_capacity_tons: 3000,
    available_capacity_tons: 1100,
    temp_range_c: '2°C to 10°C',
    humidity_range_pct: '50% to 65%',
    price_per_ton_day: 50,
    contact_phone: '+91 98940 12345',
  },
];

export const SEED_LOGISTICS: LogisticsRequest[] = [
  {
    id: 'log-01',
    order_id: 'ord-1001',
    pickup_location: 'Central Storage, Thanjavur, TN',
    delivery_location: 'FreshGro Warehouse, Bengaluru, KA',
    crop_name: 'Organic Finger Turmeric',
    weight_kg: 2500,
    vehicle_type: 'Refrigerated Van (3 Ton)',
    status: 'in_transit',
    tracking_code: 'TRK-TN-KA-2026-9901',
    driver_name: 'Murugan P.',
    driver_phone: '+91 97899 11223',
    created_at: '2026-02-26T08:00:00Z',
  },
];
