'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CalendarDays, CheckCircle2, Circle, ClipboardList, Loader2 } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import { api, Cultivation } from '@/lib/api';
export default function CropTimeline({params}:{params:{cropId:string}}){
 const [crop,setCrop]=useState<Cultivation|null>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{api.cultivations().then(items=>setCrop(items.find(x=>x.id===params.cropId)||null)).finally(()=>setLoading(false))},[params.cropId]);
 const events=[['Plan created','Cultivation record created in AgriMark.'],['Field preparation','Review soil, water source and planned inputs.'],['Crop scouting','Capture observations from the field as the crop develops.'],['Harvest','Record the batch and create a traceable produce lot.']];
 return <AppShell>{loading?<div className="loading"><Loader2 size={24}/></div>:!crop?<div className="card empty">Crop plan not found.<Link href="/farmer/dashboard" className="btn btn-secondary" style={{marginTop:16}}>Dashboard</Link></div>:<><div className="page-title"><div><Link href={`/farm/${crop.farm_id}`} style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Farm passport</Link><div className="eyebrow" style={{marginTop:14}}>Smart crop timeline</div><h1>Crop cycle</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Season: {crop.season||'—'} · Status: {crop.status||'planned'} · Area: {crop.area_acres??'—'} acres</p></div></div><div className="card"><div style={{display:'grid',gap:0}}>{events.map(([title,body],i)=><div key={title} style={{display:'grid',gridTemplateColumns:'42px 1fr',gap:14,padding:'17px 0',borderBottom:i===events.length-1?'none':'1px solid #eee9de'}}><div style={{width:34,height:34,borderRadius:12,display:'grid',placeItems:'center',background:i===0?'#edf4ef':'#fbfaf7',color:'#1B4D3E'}}>{i===0?<CheckCircle2 size={17}/>:i===3?<CalendarDays size={17}/>:<Circle size={17}/>}</div><div><strong>{title}</strong><div style={{color:'#707873',fontSize:12,marginTop:4,lineHeight:1.6}}>{body}</div></div></div>)}</div></div><div className="grid-3" style={{marginTop:16}}><Link className="card" href={`/crops/${crop.id}/scout`}><ClipboardList size={19} color="#3E7B54"/><h3 style={{marginTop:12}}>Scout field</h3><p>Capture pest, disease, soil and plant observations.</p></Link><Link className="card" href={`/farm/${crop.farm_id}/inputs`}><ClipboardList size={19} color="#3E7B54"/><h3 style={{marginTop:12}}>Track inputs</h3><p>Keep application, quantity and cost records linked.</p></Link><Link className="card" href={`/crops/${crop.id}/harvest/new`}><CalendarDays size={19} color="#3E7B54"/><h3 style={{marginTop:12}}>Record harvest</h3><p>Convert the crop cycle into a traceable produce lot.</p></Link></div></>}
 </AppShell>;
}
