'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Droplets, Loader2, MapPin, Ruler, Sprout } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import { api, Farm } from '@/lib/api';
export default function FarmDetailPage({params}:{params:{id:string}}){
 const [farm,setFarm]=useState<Farm|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{api.me().then(me=>api.farms(me.id)).then(farms=>setFarm(farms.find(f=>f.id===params.id)||null)).catch(e=>setError(e instanceof Error?e.message:'Unable to load farm.')).finally(()=>setLoading(false))},[params.id]);
 return <AppShell>{loading?<div className="loading"><Loader2 size={24}/></div>:error?<div className="error">{error}</div>:!farm?<div className="card empty">Farm not found.<Link href="/farmer/farms" className="btn btn-secondary" style={{marginTop:16}}>Back to farms</Link></div>:<><div className="page-title"><div><Link href="/farmer/farms" style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> My farms</Link><div className="eyebrow" style={{marginTop:14}}>Farm passport</div><h1>{farm.name||'Untitled farm'}</h1><p style={{color:'#707873',margin:'6px 0 0'}}><MapPin size={14} style={{verticalAlign:'-2px'}}/> {[farm.village,farm.district,farm.state].filter(Boolean).join(', ')||'Location not added'}</p></div><Link href={`/farm/${farm.id}/crops/new`} className="btn btn-primary"><Sprout size={16}/> Plan crop</Link></div><div className="stats"><div className="stat-card"><small>Area</small><strong>{farm.area_acres??'—'} ac</strong></div><div className="stat-card"><small>Soil</small><strong style={{fontSize:20,fontFamily:'inherit'}}>{farm.soil_type||'—'}</strong></div><div className="stat-card"><small>Irrigation</small><strong style={{fontSize:20,fontFamily:'inherit'}}>{farm.irrigation_type||'—'}</strong></div><div className="stat-card"><small>Soil pH</small><strong>{farm.soil_ph??'—'}</strong></div></div><div className="grid-3"><div className="card"><div className="icon-tile"><Ruler size={19}/></div><h3>Land profile</h3><p>Area, district and boundary details are kept with the farm record for future planning.</p></div><div className="card"><div className="icon-tile"><Droplets size={19}/></div><h3>Water profile</h3><p>{farm.irrigation_type?`Primary irrigation: ${farm.irrigation_type}.`:'Add your irrigation source to improve crop planning and task recommendations.'}</p></div><div className="card"><div className="icon-tile"><Sprout size={19}/></div><h3>Next step</h3><p>Plan a cultivation, then use scouting, inputs and harvest records to build the crop timeline.</p><Link href={`/farm/${farm.id}/crops/new`} className="side-link" style={{paddingLeft:0,marginTop:10}}>Plan crop <ArrowLeft size={14} style={{transform:'rotate(180deg)'}}/></Link></div></div></>}
 </AppShell>;
}
