'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, Languages, Volume2 } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import ActionButton from '@/app/_components/ActionButton';
import { supabase } from '@/lib/supabase';

const languages=[['en-IN','English'],['hi-IN','हिन्दी'],['mr-IN','मराठी'],['pa-IN','ਪੰਜਾਬੀ'],['te-IN','తెలుగు'],['ta-IN','தமிழ்'],['kn-IN','ಕನ್ನಡ'],['ml-IN','മലയാളം'],['gu-IN','ગુજરાતી'],['bn-IN','বাংলা']];
export default function LanguagePage(){const[selected,setSelected]=useState('en-IN');const[saved,setSaved]=useState(false);const[error,setError]=useState('');const apply=async()=>{setError('');try{localStorage.setItem('agrimark_language',selected);const{data:{user}}=await supabase.auth.getUser();if(user){await supabase.schema('stitch_app').from('user_profiles').upsert({user_id:user.id,language_code:selected,updated_at:new Date().toISOString()},{onConflict:'user_id'});}setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Unable to save language preference.')}};return <AppShell><div className="page-title"><div><Link href="/farmer/dashboard" style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Dashboard</Link><div className="eyebrow" style={{marginTop:14}}>Language & voice</div><h1>Choose your language.</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Use the language that feels natural while working in AgriMark.</p></div></div><div className="card" style={{maxWidth:760}}><div style={{display:'flex',alignItems:'center',gap:10,marginBottom:16}}><Languages size={20}/><strong>Available languages</strong></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}>{languages.map(([code,label])=><ActionButton key={code} type="button" actionName={`language:select:${code}`} onClick={()=>{setSelected(code);setSaved(false)}} style={{padding:14,borderRadius:14,border:selected===code?'2px solid #1B4D3E':'1px solid #e2ddd1',background:selected===code?'#edf5ef':'#fff',textAlign:'left',fontWeight:700}}>{selected===code?<CheckCircle2 size={16}/>:<Languages size={16}/>} {label}</ActionButton>)}</div>{error&&<div className="error" style={{marginTop:15}}>{error}</div>}{saved&&<div style={{marginTop:15,padding:12,borderRadius:12,background:'#edf5ef',color:'#257042',fontSize:12}}>Language preference applied.</div>}<ActionButton type="button" className="btn btn-primary" style={{marginTop:16}} onClick={apply} actionName="language:apply"><Volume2 size={16}/> Apply language</ActionButton></div></AppShell>}
