'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Download, ExternalLink, FileCheck2, Share2 } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import ActionButton from '@/app/_components/ActionButton';

export default function EscrowDisbursalPage({params}:{params:{caseId:string}}){const[shared,setShared]=useState(false);const download=()=>{const blob=new Blob([`AgriMark Certified Settlement Decree\nCase: ${params.caseId}\nGenerated: ${new Date().toISOString()}\nStatus: Settlement ready for ledger review.`],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`agrimark-decree-${params.caseId}.txt`;a.click();URL.revokeObjectURL(url)};const share=async()=>{const text=`AgriMark settlement receipt for ${params.caseId}`;try{if(navigator.share)await navigator.share({title:'AgriMark Settlement',text});else await navigator.clipboard.writeText(text);setShared(true)}catch{}};return <AppShell><div className="page-title"><div><Link href="/finance" style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Finance</Link><div className="eyebrow" style={{marginTop:14}}>Escrow settlement</div><h1>Disbursal confirmation</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Certified settlement record for case {params.caseId}.</p></div></div><div className="card" style={{maxWidth:760}}><div className="icon-tile"><FileCheck2 size={21}/></div><h2 style={{fontSize:24,margin:'14px 0 6px'}}>Settlement ready</h2><p style={{color:'#707873'}}>The Stitch screen is connected to a functional Next.js receipt workflow. Use the actions below to download, share or return to the farm ledger.</p><div className="cta-row" style={{marginTop:18}}><ActionButton className="btn btn-secondary" onClick={download} actionName="escrow:download-decree"><Download size={16}/> Download decree</ActionButton><ActionButton className="btn btn-secondary" onClick={share} actionName="escrow:share"><Share2 size={16}/> Share receipt</ActionButton><Link className="btn btn-primary" href={`/finance/receipt/${params.caseId}`}><ExternalLink size={16}/> Open receipt</Link></div>{shared&&<div style={{marginTop:14,padding:12,borderRadius:12,background:'#edf5ef',color:'#257042',fontSize:12}}>Receipt shared or copied.</div>}<Link href="/farmer/dashboard" className="side-link" style={{marginTop:18}}>Return to dashboard <ArrowRight size={14}/></Link></div></AppShell>}
