'use client';
import { useState } from 'react';
import { ArrowLeft, Camera, Loader2, Save, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import AppShell from '@/app/_components/AppShell';
export default function ScoutPage({params}:{params:{cropId:string}}){
 const [form,setForm]=useState({observation_type:'routine_scout',crop_stage:'',plant_health:'Good',pest_pressure:'Low',disease_pressure:'Low',notes:''});const [saved,setSaved]=useState(false);const update=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 return <AppShell><div className="page-title"><div><Link href={`/crops/${params.cropId}/timeline`} style={{display:'inline-flex',alignItems:'center',gap:7,fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Crop timeline</Link><div className="eyebrow" style={{marginTop:14}}>Field scouting</div><h1>Capture a field observation.</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Keep the note lightweight enough to use while standing in the field.</p></div></div><div className="grid-3"><div className="card"><div className="icon-tile"><Camera size={20}/></div><h3>Camera-ready</h3><p>Use the device camera in the next capture iteration to attach evidence to this observation.</p><button className="btn btn-secondary" style={{marginTop:14}} disabled><Camera size={16}/> Open camera</button></div><div className="card" style={{gridColumn:'span 2'}}><form className="form-grid" onSubmit={e=>{e.preventDefault();setSaved(true)}}><div className="field"><label>Observation type</label><select value={form.observation_type} onChange={e=>update('observation_type',e.target.value)}><option value="routine_scout">Routine scout</option><option value="pest">Pest check</option><option value="disease">Disease check</option><option value="irrigation">Irrigation check</option></select></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Crop stage</label><input value={form.crop_stage} onChange={e=>update('crop_stage',e.target.value)} placeholder="e.g. Vegetative"/></div><div className="field"><label>Plant health</label><select value={form.plant_health} onChange={e=>update('plant_health',e.target.value)}><option>Good</option><option>Watch</option><option>Concern</option></select></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Pest pressure</label><select value={form.pest_pressure} onChange={e=>update('pest_pressure',e.target.value)}><option>Low</option><option>Medium</option><option>High</option></select></div><div className="field"><label>Disease pressure</label><select value={form.disease_pressure} onChange={e=>update('disease_pressure',e.target.value)}><option>Low</option><option>Medium</option><option>High</option></select></div></div><div className="field"><label>Field notes</label><textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="What did you see?"/></div>{saved&&<div style={{padding:12,borderRadius:12,background:'#edf5ef',color:'#257042',fontSize:12}}><ShieldCheck size={15} style={{verticalAlign:'-3px',marginRight:5}}/> Observation captured in the Stitch workflow. Connect the form submission to the field-observations API next.</div>}<button className="btn btn-primary" type="submit"><Save size={16}/> Save observation</button></form></div></div></AppShell>;
}
