'use client';
import React,{useEffect,useState} from 'react';
import {dataService} from '@/lib/data-service';
import {LogisticsRequest} from '@/types';
import {ArrowLeft,MapPin,Navigation,Truck,ShieldCheck,RefreshCw} from 'lucide-react';
import Link from 'next/link';
export default function TrackPage({params}:{params:{orderId:string}}){
 const [job,setJob]=useState<LogisticsRequest|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{void (async()=>{setLoading(true);try{const rows=await dataService.getLogisticsRequests();setJob(rows.find(r=>r.order_id===params.orderId)||null);}finally{setLoading(false);}})();},[params.orderId]);
 return <div className="space-y-5"><Link href="/logistics/deliveries" className="inline-flex items-center gap-2 text-xs text-gray-400 hover:text-white"><ArrowLeft className="h-4 w-4"/> Delivery Board</Link><section className="rounded-2xl border border-[#1e2d26] bg-[#121a16] p-5"><div className="flex items-center gap-2 text-emerald-400"><Navigation className="h-5 w-5"/><span className="text-[10px] font-bold uppercase tracking-widest">Shipment Tracking</span></div>{loading?<div className="mt-6 h-40 animate-pulse rounded-xl bg-[#0a0f0d]"/>:!job?<div className="mt-6 rounded-xl border border-dashed border-[#294238] py-14 text-center"><p className="text-sm font-semibold text-gray-300">Shipment not found</p><p className="mt-1 text-xs text-gray-500">No logistics request is linked to this order yet.</p></div>:<><div className="mt-4 flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><h1 className="text-xl font-bold text-white">{job.crop_name} · {Number(job.weight_kg||0).toLocaleString('en-IN')} kg</h1><p className="mt-1 font-mono text-[10px] text-gray-500">{job.tracking_code}</p></div><span className="rounded-full border border-emerald-800/40 bg-emerald-950/40 px-3 py-1 text-[10px] font-bold uppercase text-emerald-300">{job.status.replace('_',' ')}</span></div><div className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#0a0f0d] p-4"><Truck className="h-4 w-4 text-emerald-400"/><p className="mt-2 text-[10px] uppercase text-gray-500">Vehicle</p><p className="mt-1 text-xs font-bold text-white">{job.vehicle_type}</p></div><div className="rounded-xl bg-[#0a0f0d] p-4"><MapPin className="h-4 w-4 text-emerald-400"/><p className="mt-2 text-[10px] uppercase text-gray-500">Pickup</p><p className="mt-1 text-xs font-bold text-white">{job.pickup_location}</p></div><div className="rounded-xl bg-[#0a0f0d] p-4"><MapPin className="h-4 w-4 text-emerald-400"/><p className="mt-2 text-[10px] uppercase text-gray-500">Destination</p><p className="mt-1 text-xs font-bold text-white">{job.delivery_location}</p></div></div><div className="mt-4 rounded-xl border border-emerald-900/40 bg-emerald-950/20 p-4 text-xs text-gray-400"><ShieldCheck className="mb-2 h-4 w-4 text-emerald-400"/>Tracking is tied to the AgriMark shipment record. GPS/sensor telemetry is displayed only when a device has reported data.</div></>}</section></div>;
}