'use client';

import { useState } from 'react';
import { Bot, Leaf, Loader2, Send, Sparkles } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import { api } from '@/lib/api';

export default function AiAssistantPage(){
 const [message,setMessage]=useState(''); const [answer,setAnswer]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const ask=async(text=message)=>{if(!text.trim()) return; setMessage(text);setError('');setBusy(true);try{const r=await api.askAi(text);setAnswer(r.answer||'AgriAI returned no answer.')}catch(e){setError(e instanceof Error?e.message:'Unable to reach AgriAI.')}finally{setBusy(false)}};
 const prompts=['What should I check before irrigating today?','How can I prepare my crop for harvest?','Help me compare my produce with the market.'];
 return <AppShell><div className="page-title"><div><div className="eyebrow">AgriAI · multilingual assistant</div><h1>Ask the farm, not a search box.</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Bring practical questions about crops, markets, operations and your AgriMark context.</p></div><span className="badge"><Sparkles size={13} style={{marginRight:4}}/> AI workspace</span></div>
 <div className="card" style={{background:'#121A16',color:'#fff',minHeight:430,padding:24,display:'flex',flexDirection:'column'}}><div style={{display:'flex',gap:12,alignItems:'center'}}><div style={{width:45,height:45,borderRadius:15,display:'grid',placeItems:'center',background:'rgba(255,255,255,.08)'}}><Bot size={21}/></div><div><div style={{fontWeight:800}}>AgriAI</div><div style={{fontSize:11,color:'rgba(255,255,255,.55)'}}>Grounded in your AgriMark workflow</div></div></div>{answer?<div style={{marginTop:24,padding:18,borderRadius:18,background:'rgba(255,255,255,.06)',lineHeight:1.75,color:'rgba(255,255,255,.84)',whiteSpace:'pre-wrap'}}>{answer}</div>:<div style={{marginTop:22,color:'rgba(255,255,255,.55)',fontSize:14,lineHeight:1.7}}>Ask about a field task, a crop decision, a market signal or how to use AgriMark. For consequential agronomic decisions, use professional local guidance alongside the assistant.</div>}{error&&<div style={{marginTop:15,padding:12,borderRadius:12,background:'rgba(185,28,28,.22)',color:'#fecaca',fontSize:12}}>{error}</div>}<div style={{marginTop:'auto'}}><div style={{display:'flex',flexWrap:'wrap',gap:8,margin:'22px 0 12px'}}>{prompts.map(p=><button key={p} onClick={()=>void ask(p)} style={{border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.06)',color:'#fff',borderRadius:12,padding:'9px 11px',fontSize:11}}>{p}</button>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:10}}><div style={{position:'relative'}}><Leaf size={16} style={{position:'absolute',left:14,top:16,color:'rgba(255,255,255,.45)'}}/><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask()}} placeholder="Ask your farming question…" style={{width:'100%',minHeight:50,border:'1px solid rgba(255,255,255,.12)',background:'rgba(255,255,255,.07)',borderRadius:14,paddingLeft:40,color:'#fff'}}/></div><button className="btn btn-gold" onClick={()=>void ask()} disabled={busy}>{busy?<Loader2 size={17}/>:<Send size={17}/>} {busy?'Thinking…':'Ask'}</button></div></div></div>
 </AppShell>
}
