'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Leaf, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { trackAction } from '@/lib/telemetry';
export default function NewFarmPage(){
 const [form,setForm]=useState({name:'',village:'',district:'',state:'Tamil Nadu',area_acres:'',soil_type:'',irrigation_type:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const update=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setError('');setBusy(true);const started=performance.now();try{const me=await api.me();const farm=await api.createFarm(me.id,{...form,area_acres:form.area_acres?Number(form.area_acres):undefined} as any);await trackAction('farm:create','/farm/new',true,Math.round(performance.now()-started),{farm_id:farm.id});window.location.assign(`/farm/${farm.id}`)}catch(err){await trackAction('farm:create','/farm/new',false,Math.round(performance.now()-started));setError(err instanceof Error?err.message:'Unable to create farm.');setBusy(false)}};
 return <div className="login-page"><div className="login-card" style={{maxWidth:760}}><Link href="/farmer/farms" style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> My farms</Link><div style={{marginTop:22}}><div className="eyebrow">Add farm land survey</div><h2 style={{fontSize:30,margin:'8px 0'}}>Create your farm passport</h2><p style={{color:'#727a75'}}>Start with the details you know. Soil, boundary and crop information can be expanded later.</p></div><form onSubmit={submit} className="form-grid" style={{marginTop:20}}>{error&&<div className="error" aria-live="polite">{error}</div>}<div className="field"><label>Farm name</label><input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. Shree Ganesh Krishi Farm" required disabled={busy}/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Village</label><input value={form.village} onChange={e=>update('village',e.target.value)} placeholder="Village" disabled={busy}/></div><div className="field"><label>District</label><input value={form.district} onChange={e=>update('district',e.target.value)} placeholder="District" disabled={busy}/></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>State</label><input value={form.state} onChange={e=>update('state',e.target.value)} disabled={busy}/></div><div className="field"><label>Area (acres)</label><input type="number" step="0.01" min="0" value={form.area_acres} onChange={e=>update('area_acres',e.target.value)} placeholder="0.00" disabled={busy}/></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="field"><label>Soil type</label><select value={form.soil_type} onChange={e=>update('soil_type',e.target.value)} disabled={busy}><option value="">Select</option><option>Red soil</option><option>Black soil</option><option>Alluvial soil</option><option>Loamy soil</option><option>Sandy soil</option></select></div><div className="field"><label>Irrigation</label><select value={form.irrigation_type} onChange={e=>update('irrigation_type',e.target.value)} disabled={busy}><option value="">Select</option><option>Drip</option><option>Sprinkler</option><option>Canal</option><option>Well</option><option>Rainfed</option></select></div></div><div style={{padding:14,borderRadius:15,background:'#edf5ef',color:'#365744',fontSize:12}}><CheckCircle2 size={15} style={{verticalAlign:'-3px',marginRight:6}}/>Add only accurate information. AgriMark can enrich this record through later surveys and observations.</div><button type="submit" className="btn btn-primary" disabled={busy}>{busy?<Loader2 size={16} style={{animation:'spin 1s linear infinite'}}/>:<ArrowRight size={16}/>} {busy?'Saving…':'Save farm passport'}</button></form></div></div>
}
