'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Loader2, Sprout } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import { api } from '@/lib/api';
export default function NewCropPage({params}:{params:{id:string}}){
 const [crops,setCrops]=useState<any[]>([]);const [cropId,setCropId]=useState('');const [season,setSeason]=useState('Kharif');const [area,setArea]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL||'https://agrimark-api.onrender.com/api/v1'}/core/crops`).then(r=>r.json()).then(d=>setCrops(d.items||d||[])).catch(()=>setCrops([]))},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const created=await api.createCultivation({farm_id:params.id,crop_id:cropId,season,area_acres:area?Number(area):undefined,status:'planned'} as any);window.location.assign(`/crops/${created.id}/timeline`)}catch(e){setError(e instanceof Error?e.message:'Unable to create crop plan.')}finally{setBusy(false)}};
 return <AppShell><div className="page-title"><div><Link href={`/farm/${params.id}`} style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Farm passport</Link><div className="eyebrow" style={{marginTop:14}}>Crop plan · Phenology</div><h1>Plan your next crop.</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Start the cultivation record that will power your crop timeline.</p></div></div><div className="card" style={{maxWidth:760}}><form onSubmit={submit} className="form-grid">{error&&<div className="error">{error}</div>}<div className="field"><label>Crop</label><select value={cropId} onChange={e=>setCropId(e.target.value)} required><option value="">Select a crop</option>{crops.map(c=><option value={c.id} key={c.id}>{c.name||c.crop_name}</option>)}</select></div><div className="field"><label>Season</label><select value={season} onChange={e=>setSeason(e.target.value)}><option>Kharif</option><option>Rabi</option><option>Zaid</option><option>Year-round</option></select></div><div className="field"><label>Area for this crop (acres)</label><input type="number" min="0" step="0.01" value={area} onChange={e=>setArea(e.target.value)} placeholder="Optional"/></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div className="card" style={{background:'#fbfaf7'}}><CalendarDays size={20} color="#3E7B54"/><div style={{fontWeight:800,marginTop:10}}>Crop timeline</div><p style={{marginTop:6}}>Sowing, field tasks, scouting and expected harvest stay linked to this record.</p></div><div className="card" style={{background:'#fbfaf7'}}><Sprout size={20} color="#3E7B54"/><div style={{fontWeight:800,marginTop:10}}>Farm context</div><p style={{marginTop:6}}>Keep crop decisions attached to the correct farm land record.</p></div></div><button className="btn btn-primary" type="submit" disabled={busy}>{busy?<Loader2 size={16}/>:<ArrowRight size={16}/>} {busy?'Creating plan…':'Create crop plan'}</button></form></div></AppShell>;
}
