'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Download, QrCode, Share2 } from 'lucide-react';
import AppShell from '@/app/_components/AppShell';
import ActionButton from '@/app/_components/ActionButton';

export default function ReceiptPage({params}:{params:{receiptId:string}}){const[message,setMessage]=useState('');const download=()=>{const blob=new Blob([`AgriMark GST / Mandi Receipt\nReceipt: ${params.receiptId}\nGenerated: ${new Date().toISOString()}`],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`agrimark-receipt-${params.receiptId}.txt`;a.click();URL.revokeObjectURL(url)};const share=async()=>{try{if(navigator.share)await navigator.share({title:'AgriMark Receipt',text:`Receipt ${params.receiptId}`});else await navigator.clipboard.writeText(`Receipt ${params.receiptId}`);setMessage('Receipt shared or copied.')}catch{setMessage('Sharing was cancelled.')}};return <AppShell><div className="page-title"><div><Link href={`/finance/settlement/${params.receiptId}`} style={{display:'inline-flex',gap:7,alignItems:'center',fontSize:12,fontWeight:800,color:'#68716b'}}><ArrowLeft size={15}/> Settlement</Link><div className="eyebrow" style={{marginTop:14}}>Escrow settlement payment receipt</div><h1>Payment receipt</h1><p style={{color:'#707873',margin:'6px 0 0'}}>Receipt {params.receiptId} is ready for your digital ledger.</p></div></div><div className="card" style={{maxWidth:760}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'}}><div><div className="badge">SETTLED</div><h2 style={{fontSize:30,margin:'12px 0 5px'}}>₹0.00</h2><p style={{color:'#707873'}}>Settlement amount is sourced from the production transaction workflow.</p></div><div className="icon-tile" style={{width:100,height:100}}><QrCode size={70}/></div></div><div className="cta-row" style={{marginTop:20}}><ActionButton className="btn btn-primary" onClick={download} actionName="receipt:download"><Download size={16}/> Download receipt</ActionButton><ActionButton className="btn btn-secondary" onClick={share} actionName="receipt:share"><Share2 size={16}/> Share receipt</ActionButton></div>{message&&<div style={{marginTop:14,padding:12,borderRadius:12,background:'#edf5ef',color:'#257042',fontSize:12}}>{message}</div>}<Link href="/finance" className="side-link" style={{marginTop:18}}>Back to Khaata</Link></div></AppShell>}
